services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # volumes:
    #   - .:/app
    container_name: login_app
    ports:
      - ${EXTERN_PORT}:${INTER_PORT}
    environment:
      - EXPOSE_PORT=${INTER_PORT}