services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # volumes:
    #   - .:/app
    container_name: login_backend_app
    depends_on:
      - db
    ports:
      - ${BACKEND_EXTERNAL_PORT}:${BACKEND_INTERAL_PORT}
    environment:
      - EXPOSE_PORT=${BACKEND_INTERAL_PORT}
      - SUPER_USER_NAME=${BACKEND_SUPER_USER_NAME}
      - SUPER_USER_EMAIL=${BACKEND_SUPER_USER_EMAIL}
      - SUPER_USER_PASSWORD=${BACKEND_SUPER_USER_PASSWORD}
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: login_frontend_app
    depends_on:
      - backend
    ports:
      - ${FRONTEND_EXTERNAL_PORT}:${FRONTEND_INTERNAL_PORT}
    environment:
      - EXPOSE_PORT=${FRONTEND_INTERNAL_PORT}
  db:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgres:16-alpine
    restart: always
    ports:
      - ${POSTGRES_PORT_EXPOSE}:${POSTGRES_PORT_INTERN}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=${POSTGRES_DB}

  pgAdmin:
    container_name: ${PGADMIN_CONTAINER_NAME}
    depends_on:
      - db
    image: dpage/pgadmin4:8.11.0
    restart: always
    ports:
      - "${PGADMIN_PORT_EXPOSE}:${PGADMIN_PORT_INTERN}"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      # es necesario cambiar los permisos para evitar conflictos
      # sudo chown -R 5050:5050 pgadmin/
    environment:
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}